# Generated by Django 3.1.6 on 2023-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mstuser',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fnm', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=40)),
                ('pwd', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
