# Generated by Django 3.1.6 on 2023-11-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='course1',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('courseicon', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='batch1',
            fields=[
                ('batchid', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('batchtime', models.CharField(max_length=30)),
                ('facultyname', models.CharField(max_length=40)),
                ('batchstatus', models.IntegerField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course1')),
            ],
        ),
    ]
