# Generated by Django 3.1.6 on 2023-11-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='admission',
            new_name='admissionno',
        ),
    ]
